apiVersion: v1
kind: List
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: project1
  spec:
    destination:
      server: https://kubernetes.default.svc
      namespace: check1
    source:
      repoURL: https://github.com/valipashask26/argo-cd-learnings.git
      targetRevision: master
      path: k8s-manifest
    project: default
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: project2
  spec:
    destination:
      server: https://kubernetes.default.svc
      namespace: check2
    source:
      repoURL: https://github.com/valipashask26/argo-cd-learnings.git
      targetRevision: master
      path: k8s-manifest
    project: default
